apiVersion: v1
kind: Service
metadata:
  name: readyset-cache-{target_name}
  namespace: {namespace}
  labels:
    app: readyset-cache-{target_name}
    managed-by: rdst
spec:
  type: ClusterIP
  ports:
  - port: {readyset_port}
    targetPort: {readyset_port}
    protocol: TCP
    name: readyset
  selector:
    app: readyset-cache-{target_name}
