"""Audit feature slice."""

from .capture_service import CaptureService, _normalize, _parse_duration
from .events import (
    AuditCompleteEvent,
    AuditDiffEvent,
    AuditErrorEvent,
    AuditEvent,
    AuditInput,
    AuditLlmInsightsEvent,
    AuditMetricsCollectedEvent,
    AuditOptions,
    AuditSnapshotSavedEvent,
    AuditStatusEvent,
    AuditTargetCompleteEvent,
    AuditTargetErrorEvent,
    AuditTargetStartEvent,
    WorkloadAnalysisProgressEvent,
    WorkloadCaptureCompleteEvent,
    WorkloadCaptureProgressEvent,
    WorkloadCompleteEvent,
    WorkloadConnectedEvent,
    WorkloadErrorEvent,
    WorkloadEvent,
    WorkloadInput,
    WorkloadOptions,
    WorkloadQueriesSavedEvent,
    WorkloadSnapshotEvent,
    WorkloadStatusEvent,
)
from .models import (
    AuditMetrics,
    AuditResult,
    CacheOpportunityScore,
    DatabaseSnapshot,
    IntermediateSnapshot,
    SizingAssessment,
    TableStats,
    WorkloadAnalysis,
    WorkloadDiff,
    WorkloadQuery,
    WorkloadRun,
)
from .prompts import build_audit_capture_prompt
from .query_stats import collect_mysql_digest_stats, collect_pg_stat_statements, compute_snapshot_delta
from .service import AuditService
from .storage import AuditStorage

__all__ = [
    "AuditCompleteEvent",
    "AuditDiffEvent",
    "AuditErrorEvent",
    "AuditEvent",
    "AuditInput",
    "AuditLlmInsightsEvent",
    "AuditMetrics",
    "AuditMetricsCollectedEvent",
    "AuditOptions",
    "AuditResult",
    "AuditService",
    "AuditSnapshotSavedEvent",
    "AuditStatusEvent",
    "AuditStorage",
    "AuditTargetCompleteEvent",
    "AuditTargetErrorEvent",
    "AuditTargetStartEvent",
    "CacheOpportunityScore",
    "CaptureService",
    "DatabaseSnapshot",
    "IntermediateSnapshot",
    "SizingAssessment",
    "TableStats",
    "WorkloadAnalysis",
    "WorkloadAnalysisProgressEvent",
    "WorkloadCaptureCompleteEvent",
    "WorkloadCaptureProgressEvent",
    "WorkloadCompleteEvent",
    "WorkloadConnectedEvent",
    "WorkloadDiff",
    "WorkloadErrorEvent",
    "WorkloadEvent",
    "WorkloadInput",
    "WorkloadOptions",
    "WorkloadQueriesSavedEvent",
    "WorkloadQuery",
    "WorkloadRun",
    "WorkloadSnapshotEvent",
    "WorkloadStatusEvent",
    "_normalize",
    "_parse_duration",
    "build_audit_capture_prompt",
    "collect_mysql_digest_stats",
    "collect_pg_stat_statements",
    "compute_snapshot_delta",
]
