FROM python:3.11-slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y \
    gcc make cmake zip build-essential curl tar rpm patchelf \
    ruby ruby-dev rubygems zlib1g-dev libssl-dev libffi-dev pkg-config \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel nuitka zstandard \
 && gem install --no-document fpm

COPY requirements.txt /workspace/requirements.txt
RUN pip install --no-cache-dir -r /workspace/requirements.txt

WORKDIR /workspace
