import fsExtra from "fs-extra";
import { glob } from "glob";
import { parse } from "node-html-parser";
import * as path from "node:path";

const cwd = process.cwd();
const inputDir = path.join(cwd, "svg");
const typeDir = path.join(cwd, "types");
const outputDir = path.join(cwd, "dist");

// Every app that serves the sprites from its own public directory. Discovered
// rather than hardcoded, so a checkout that only has a subset of the apps
// (e.g. a public mirror) doesn't get phantom `apps/<name>/public/icons`
// directories created for the apps it lacks.
const appIconsDirs = await glob("../../apps/*/public/icons", {
	cwd,
	absolute: true,
	onlyDirectories: true,
});

// Ensure directories exist
await fsExtra.ensureDir(outputDir);
await fsExtra.ensureDir(typeDir);

const shouldVerboseLog = process.argv.includes("--log=verbose");
const logVerbose = shouldVerboseLog ? console.log : () => {};

// Discover icon variant directories (e.g. stroke, bulk, solid)
const variantDirs = (await fsExtra.readdir(inputDir, { withFileTypes: true }))
	.filter((entry) => entry.isDirectory())
	.map((entry) => entry.name)
	.sort((a, b) => a.localeCompare(b));

if (variantDirs.length === 0) {
	console.log(`No icon variant directories found in svg/`);
	process.exit(0);
}

try {
	await generateAllVariants();
} catch (error) {
	console.error("Error generating icon files:", error);
}

async function generateAllVariants() {
	const allVariantNames: string[] = [];
	const allIconNamesByVariant: Record<string, string[]> = {};

	for (const variant of variantDirs) {
		const variantInputDir = path.join(inputDir, variant);
		const files: string[] = glob
			.sync("**/*.svg", { cwd: variantInputDir })
			.sort((a, b) => a.localeCompare(b));

		if (files.length === 0) {
			logVerbose(`No SVG files found in svg/${variant}, skipping`);
			continue;
		}

		allVariantNames.push(variant);
		const iconNames = files.map((file) => iconName(file));
		allIconNamesByVariant[variant] = iconNames;

		const spriteFileName = `sprite-${variant}.svg`;
		const spriteFilepath = path.join(outputDir, spriteFileName);

		const currentSprite = await safeReadFile(spriteFilepath);
		const spriteUpToDate = iconNames.every((name) => currentSprite.includes(`id="${name}"`));

		if (spriteUpToDate) {
			logVerbose(`Icons for variant "${variant}" are up to date`);
		} else {
			logVerbose(`Generating sprite for svg/${variant}`);

			await generateSvgSprite({
				files,
				inputDir: variantInputDir,
				outputPaths: [
					spriteFilepath,
					...appIconsDirs.map((dir) => path.join(dir, spriteFileName)),
				],
			});

			logVerbose(`Sprite ${spriteFileName} saved to dist and every app's public/icons`);
			console.log(`Generated ${files.length} ${variant} icons → ${spriteFileName}`);
		}
	}

	// Generate type definitions
	await generateTypes(allVariantNames, allIconNamesByVariant);

	// Generate README
	await writeIfChanged(
		path.join(inputDir, "README.md"),
		[
			`# Icons`,
			``,
			`This directory contains SVG icons organized by variant (e.g. stroke, bulk, solid).`,
			``,
			`Each subdirectory is compiled into its own sprite file using \`npm run build:icons\`.`,
			`The sprites are output to \`/public/icons/sprite-{variant}.svg\`.`,
			``,
			`Variants: ${allVariantNames.join(", ")}`,
			``,
		].join("\n")
	);
}

async function generateTypes(variants: string[], iconNamesByVariant: Record<string, string[]>) {
	const typeOutputFilepath = path.join(typeDir, "name.d.ts");

	const sections: string[] = [
		`// This file is generated by npm run build:icons`,
		``,
	];

	// Generate a union type per variant
	for (const variant of variants) {
		const typeName = `Icon${capitalize(variant)}Name`;
		const names = iconNamesByVariant[variant]!;
		const stringified = names.map((name) => `\t| ${JSON.stringify(name)}`).join("\n");
		sections.push(`export type ${typeName} =\n${stringified};\n`);
	}

	// Generate the variant type
	const variantUnion = variants.map((v) => JSON.stringify(v)).join("\n\t| ");
	sections.push(`export type IconVariant =\n\t| ${variantUnion};\n`);

	// Default IconName = stroke names (backwards compatible)
	if (iconNamesByVariant["stroke"]) {
		sections.push(`export type IconName = IconStrokeName;\n`);
	}

	await writeIfChanged(typeOutputFilepath, sections.join("\n"));
}

function capitalize(str: string): string {
	return str.charAt(0).toUpperCase() + str.slice(1);
}

function iconName(file: string): string {
	return file.replace(/\.svg$/, "").replace(/\\/g, "/");
}

/**
 * Creates a single SVG file that contains all the icons and writes it to multiple locations
 */
async function generateSvgSprite({
	files,
	inputDir,
	outputPaths,
}: {
	files: string[];
	inputDir: string;
	outputPaths: string[];
}): Promise<boolean> {
	try {
		const symbols = await Promise.all(
			files.map(async (file: string) => {
				const input = await fsExtra.readFile(path.join(inputDir, file), "utf8");
				const root = parse(input);

				const svg = root.querySelector("svg");
				if (!svg) throw new Error(`No SVG element found in ${file}`);

				svg.tagName = "symbol";
				svg.setAttribute("id", iconName(file));
				svg.removeAttribute("xmlns");
				svg.removeAttribute("xmlns:xlink");
				svg.removeAttribute("version");
				svg.removeAttribute("width");
				svg.removeAttribute("height");

				// Replace hardcoded fill colors with currentColor so CSS can control the color
				for (const el of svg.querySelectorAll("[fill]")) {
					const fill = el.getAttribute("fill");
					if (fill && fill !== "none" && fill !== "currentColor") {
						el.setAttribute("fill", "currentColor");
					}
				}

				return svg.toString().trim();
			})
		);

		const output = [
			`<?xml version="1.0" encoding="UTF-8"?>`,
			`<!-- This file is generated by npm run build:icons -->`,
			`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">`,
			`<defs>`, // for semantics: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs
			...symbols,
			`</defs>`,
			`</svg>`,
			"", // trailing newline
		].join("\n");

		// Write to multiple output paths
		for (const outputPath of outputPaths) {
			await writeIfChanged(outputPath, output);
		}

		return true;
	} catch (error) {
		console.error("Error generating SVG sprite:", error);
		throw error;
	}
}

/**
 * Writes new content to a file if it has changed.
 */
async function writeIfChanged(filepath: string, newContent: string): Promise<boolean> {
	try {
		const currentContent = await safeReadFile(filepath);
		if (currentContent === newContent) return false;
		await fsExtra.writeFile(filepath, newContent, "utf8");
		return true;
	} catch (error) {
		console.error(`Error writing to ${filepath}:`, error);
		throw error;
	}
}

/**
 * Reads a file and returns its content. If the file does not exist, returns an empty string.
 */
async function safeReadFile(filepath: string): Promise<string> {
	try {
		return await fsExtra.readFile(filepath, "utf8");
	} catch {
		return ""; // Return an empty string if the file doesn't exist
	}
}
