import fsExtra from "fs-extra";
import { glob } from "glob";
import { parse } from "node-html-parser";
import * as path from "node:path";

const cwd = process.cwd();
const inputDir = path.join(cwd, "svg");
const inputDirRelative = path.relative(cwd, inputDir);
const typeDir = path.join(cwd, "types");
const outputDir = path.join(cwd, "dist");

// Paths for cloud and marketing public directories
const cloudIconsDir = path.join(cwd, "../../apps/cloud/public/icons");
const marketingIconsDir = path.join(cwd, "../../apps/marketing/public/icons");

// Ensure directories exist
await fsExtra.ensureDir(outputDir);
await fsExtra.ensureDir(typeDir);
await fsExtra.ensureDir(cloudIconsDir);
await fsExtra.ensureDir(marketingIconsDir);

const files: string[] = glob.sync("**/*.svg", { cwd: inputDir }).sort((a, b) => a.localeCompare(b));

const shouldVerboseLog = process.argv.includes("--log=verbose");
const logVerbose = shouldVerboseLog ? console.log : () => {};

if (files.length === 0) {
  console.log(`No SVG files found in ${inputDirRelative}`);
} else {
  try {
    await generateIconFiles();
  } catch (error) {
    console.error("Error generating icon files:", error);
  }
}

async function generateIconFiles() {
  const spriteFilepath = path.join(outputDir, "sprite.svg");
  const typeOutputFilepath = path.join(typeDir, "name.d.ts");

  const currentSprite = await safeReadFile(spriteFilepath);
  const currentTypes = await safeReadFile(typeOutputFilepath);

  const iconNames = files.map((file) => iconName(file));

  const spriteUpToDate = iconNames.every((name) => currentSprite.includes(`id="${name}"`));
  const typesUpToDate = iconNames.every((name) => currentTypes.includes(`"${name}"`));

  if (spriteUpToDate && typesUpToDate) {
    logVerbose(`Icons are up to date`);
    return;
  }

  logVerbose(`Generating sprite for ${inputDirRelative}`);

  // Generate the sprite content
  const spriteChanged = await generateSvgSprite({
    files,
    inputDir,
    outputPaths: [
      spriteFilepath,
      path.join(cloudIconsDir, "sprite.svg"),
      path.join(marketingIconsDir, "sprite.svg"),
    ],
  });

  logVerbose(`Sprite saved to dist, cloud/public/icons, and marketing/public/icons`);

  const stringifiedIconNames = iconNames.map((name) => JSON.stringify(name));

  const typeOutputContent = `// This file is generated by npm run build:icons\n\nexport type IconName =\n\t| ${stringifiedIconNames.join("\n\t| ")};\n`;
  const typesChanged = await writeIfChanged(typeOutputFilepath, typeOutputContent);

  logVerbose(`Types saved to ${path.relative(cwd, typeOutputFilepath)}`);

  const readmeChanged = await writeIfChanged(
    path.join(inputDir, "README.md"),
    `# Icons\n\nThis directory contains SVG icons that are used by the app.\n\nEverything in this directory is made into a sprite using \`npm run build:icons\`. This file will show in /public/icons/sprite.svg\n`
  );

  if (spriteChanged || typesChanged || readmeChanged) {
    console.log(`Generated ${files.length} icons`);
  }
}

function iconName(file: string): string {
  return file.replace(/\.svg$/, "").replace(/\\/g, "/");
}

/**
 * Creates a single SVG file that contains all the icons and writes it to multiple locations
 */
async function generateSvgSprite({
  files,
  inputDir,
  outputPaths,
}: {
  files: string[];
  inputDir: string;
  outputPaths: string[];
}): Promise<boolean> {
  try {
    const symbols = await Promise.all(
      files.map(async (file: string) => {
        const input = await fsExtra.readFile(path.join(inputDir, file), "utf8");
        const root = parse(input);

        const svg = root.querySelector("svg");
        if (!svg) throw new Error(`No SVG element found in ${file}`);

        svg.tagName = "symbol";
        svg.setAttribute("id", iconName(file));
        svg.removeAttribute("xmlns");
        svg.removeAttribute("xmlns:xlink");
        svg.removeAttribute("version");
        svg.removeAttribute("width");
        svg.removeAttribute("height");

        return svg.toString().trim();
      })
    );

    const output = [
      `<?xml version="1.0" encoding="UTF-8"?>`,
      `<!-- This file is generated by npm run build:icons -->`,
      `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">`,
      `<defs>`, // for semantics: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs
      ...symbols,
      `</defs>`,
      `</svg>`,
      "", // trailing newline
    ].join("\n");

    // Write to multiple output paths
    for (const outputPath of outputPaths) {
      await writeIfChanged(outputPath, output);
    }

    return true;
  } catch (error) {
    console.error("Error generating SVG sprite:", error);
    throw error;
  }
}

/**
 * Writes new content to a file if it has changed.
 */
async function writeIfChanged(filepath: string, newContent: string): Promise<boolean> {
  try {
    const currentContent = await safeReadFile(filepath);
    if (currentContent === newContent) return false;
    await fsExtra.writeFile(filepath, newContent, "utf8");
    return true;
  } catch (error) {
    console.error(`Error writing to ${filepath}:`, error);
    throw error;
  }
}

/**
 * Reads a file and returns its content. If the file does not exist, returns an empty string.
 */
async function safeReadFile(filepath: string): Promise<string> {
  try {
    return await fsExtra.readFile(filepath, "utf8");
  } catch {
    return ""; // Return an empty string if the file doesn't exist
  }
}
