/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopRouteImport } from './routes/top'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReadysetRouteImport } from './routes/readyset'
import { Route as QueryRegistryRouteImport } from './routes/query-registry'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DevSettingsRouteImport } from './routes/dev-settings'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadysetRoute = ReadysetRouteImport.update({
  id: '/readyset',
  path: '/readyset',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRegistryRoute = QueryRegistryRouteImport.update({
  id: '/query-registry',
  path: '/query-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSettingsRoute = DevSettingsRouteImport.update({
  id: '/dev-settings',
  path: '/dev-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/benchmark': typeof BenchmarkRoute
  '/configure': typeof ConfigureRoute
  '/dev-settings': typeof DevSettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/query-registry': typeof QueryRegistryRoute
  '/readyset': typeof ReadysetRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/top': typeof TopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/benchmark': typeof BenchmarkRoute
  '/configure': typeof ConfigureRoute
  '/dev-settings': typeof DevSettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/query-registry': typeof QueryRegistryRoute
  '/readyset': typeof ReadysetRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/top': typeof TopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/benchmark': typeof BenchmarkRoute
  '/configure': typeof ConfigureRoute
  '/dev-settings': typeof DevSettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/query-registry': typeof QueryRegistryRoute
  '/readyset': typeof ReadysetRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/top': typeof TopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/benchmark'
    | '/configure'
    | '/dev-settings'
    | '/onboarding'
    | '/query-registry'
    | '/readyset'
    | '/results'
    | '/scan'
    | '/schema'
    | '/top'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/benchmark'
    | '/configure'
    | '/dev-settings'
    | '/onboarding'
    | '/query-registry'
    | '/readyset'
    | '/results'
    | '/scan'
    | '/schema'
    | '/top'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/benchmark'
    | '/configure'
    | '/dev-settings'
    | '/onboarding'
    | '/query-registry'
    | '/readyset'
    | '/results'
    | '/scan'
    | '/schema'
    | '/top'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  BenchmarkRoute: typeof BenchmarkRoute
  ConfigureRoute: typeof ConfigureRoute
  DevSettingsRoute: typeof DevSettingsRoute
  OnboardingRoute: typeof OnboardingRoute
  QueryRegistryRoute: typeof QueryRegistryRoute
  ReadysetRoute: typeof ReadysetRoute
  ResultsRoute: typeof ResultsRoute
  ScanRoute: typeof ScanRoute
  SchemaRoute: typeof SchemaRoute
  TopRoute: typeof TopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyset': {
      id: '/readyset'
      path: '/readyset'
      fullPath: '/readyset'
      preLoaderRoute: typeof ReadysetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-registry': {
      id: '/query-registry'
      path: '/query-registry'
      fullPath: '/query-registry'
      preLoaderRoute: typeof QueryRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-settings': {
      id: '/dev-settings'
      path: '/dev-settings'
      fullPath: '/dev-settings'
      preLoaderRoute: typeof DevSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  BenchmarkRoute: BenchmarkRoute,
  ConfigureRoute: ConfigureRoute,
  DevSettingsRoute: DevSettingsRoute,
  OnboardingRoute: OnboardingRoute,
  QueryRegistryRoute: QueryRegistryRoute,
  ReadysetRoute: ReadysetRoute,
  ResultsRoute: ResultsRoute,
  ScanRoute: ScanRoute,
  SchemaRoute: SchemaRoute,
  TopRoute: TopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
