/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopRouteImport } from './routes/top'
import { Route as TestRouteImport } from './routes/test'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QueryRegistryRouteImport } from './routes/query-registry'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GuardsRouteImport } from './routes/guards'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DevSettingsRouteImport } from './routes/dev-settings'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabQueriesVariantRouteImport } from './routes/lab.queries.$variant'
import { Route as AuditRunsRunIdRouteImport } from './routes/audit_.runs.$runId'

const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRegistryRoute = QueryRegistryRouteImport.update({
  id: '/query-registry',
  path: '/query-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardsRoute = GuardsRouteImport.update({
  id: '/guards',
  path: '/guards',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSettingsRoute = DevSettingsRouteImport.update({
  id: '/dev-settings',
  path: '/dev-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabQueriesVariantRoute = LabQueriesVariantRouteImport.update({
  id: '/lab/queries/$variant',
  path: '/lab/queries/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunsRunIdRoute = AuditRunsRunIdRouteImport.update({
  id: '/audit_/runs/$runId',
  path: '/audit/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/cache': typeof CacheRoute
  '/configure': typeof ConfigureRoute
  '/demo': typeof DemoRoute
  '/dev-settings': typeof DevSettingsRoute
  '/fleet': typeof FleetRoute
  '/guards': typeof GuardsRoute
  '/onboarding': typeof OnboardingRoute
  '/queries': typeof QueriesRoute
  '/query-registry': typeof QueryRegistryRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/test': typeof TestRoute
  '/top': typeof TopRoute
  '/audit/runs/$runId': typeof AuditRunsRunIdRoute
  '/lab/queries/$variant': typeof LabQueriesVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/cache': typeof CacheRoute
  '/configure': typeof ConfigureRoute
  '/demo': typeof DemoRoute
  '/dev-settings': typeof DevSettingsRoute
  '/fleet': typeof FleetRoute
  '/guards': typeof GuardsRoute
  '/onboarding': typeof OnboardingRoute
  '/queries': typeof QueriesRoute
  '/query-registry': typeof QueryRegistryRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/test': typeof TestRoute
  '/top': typeof TopRoute
  '/audit/runs/$runId': typeof AuditRunsRunIdRoute
  '/lab/queries/$variant': typeof LabQueriesVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/cache': typeof CacheRoute
  '/configure': typeof ConfigureRoute
  '/demo': typeof DemoRoute
  '/dev-settings': typeof DevSettingsRoute
  '/fleet': typeof FleetRoute
  '/guards': typeof GuardsRoute
  '/onboarding': typeof OnboardingRoute
  '/queries': typeof QueriesRoute
  '/query-registry': typeof QueryRegistryRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/schema': typeof SchemaRoute
  '/test': typeof TestRoute
  '/top': typeof TopRoute
  '/audit_/runs/$runId': typeof AuditRunsRunIdRoute
  '/lab/queries/$variant': typeof LabQueriesVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analyze'
    | '/ask'
    | '/audit'
    | '/benchmark'
    | '/cache'
    | '/configure'
    | '/demo'
    | '/dev-settings'
    | '/fleet'
    | '/guards'
    | '/onboarding'
    | '/queries'
    | '/query-registry'
    | '/results'
    | '/scan'
    | '/schema'
    | '/test'
    | '/top'
    | '/audit/runs/$runId'
    | '/lab/queries/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analyze'
    | '/ask'
    | '/audit'
    | '/benchmark'
    | '/cache'
    | '/configure'
    | '/demo'
    | '/dev-settings'
    | '/fleet'
    | '/guards'
    | '/onboarding'
    | '/queries'
    | '/query-registry'
    | '/results'
    | '/scan'
    | '/schema'
    | '/test'
    | '/top'
    | '/audit/runs/$runId'
    | '/lab/queries/$variant'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analyze'
    | '/ask'
    | '/audit'
    | '/benchmark'
    | '/cache'
    | '/configure'
    | '/demo'
    | '/dev-settings'
    | '/fleet'
    | '/guards'
    | '/onboarding'
    | '/queries'
    | '/query-registry'
    | '/results'
    | '/scan'
    | '/schema'
    | '/test'
    | '/top'
    | '/audit_/runs/$runId'
    | '/lab/queries/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AskRoute: typeof AskRoute
  AuditRoute: typeof AuditRoute
  BenchmarkRoute: typeof BenchmarkRoute
  CacheRoute: typeof CacheRoute
  ConfigureRoute: typeof ConfigureRoute
  DemoRoute: typeof DemoRoute
  DevSettingsRoute: typeof DevSettingsRoute
  FleetRoute: typeof FleetRoute
  GuardsRoute: typeof GuardsRoute
  OnboardingRoute: typeof OnboardingRoute
  QueriesRoute: typeof QueriesRoute
  QueryRegistryRoute: typeof QueryRegistryRoute
  ResultsRoute: typeof ResultsRoute
  ScanRoute: typeof ScanRoute
  SchemaRoute: typeof SchemaRoute
  TestRoute: typeof TestRoute
  TopRoute: typeof TopRoute
  AuditRunsRunIdRoute: typeof AuditRunsRunIdRoute
  LabQueriesVariantRoute: typeof LabQueriesVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-registry': {
      id: '/query-registry'
      path: '/query-registry'
      fullPath: '/query-registry'
      preLoaderRoute: typeof QueryRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guards': {
      id: '/guards'
      path: '/guards'
      fullPath: '/guards'
      preLoaderRoute: typeof GuardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-settings': {
      id: '/dev-settings'
      path: '/dev-settings'
      fullPath: '/dev-settings'
      preLoaderRoute: typeof DevSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/queries/$variant': {
      id: '/lab/queries/$variant'
      path: '/lab/queries/$variant'
      fullPath: '/lab/queries/$variant'
      preLoaderRoute: typeof LabQueriesVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit_/runs/$runId': {
      id: '/audit_/runs/$runId'
      path: '/audit/runs/$runId'
      fullPath: '/audit/runs/$runId'
      preLoaderRoute: typeof AuditRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyzeRoute: AnalyzeRoute,
  AskRoute: AskRoute,
  AuditRoute: AuditRoute,
  BenchmarkRoute: BenchmarkRoute,
  CacheRoute: CacheRoute,
  ConfigureRoute: ConfigureRoute,
  DemoRoute: DemoRoute,
  DevSettingsRoute: DevSettingsRoute,
  FleetRoute: FleetRoute,
  GuardsRoute: GuardsRoute,
  OnboardingRoute: OnboardingRoute,
  QueriesRoute: QueriesRoute,
  QueryRegistryRoute: QueryRegistryRoute,
  ResultsRoute: ResultsRoute,
  ScanRoute: ScanRoute,
  SchemaRoute: SchemaRoute,
  TestRoute: TestRoute,
  TopRoute: TopRoute,
  AuditRunsRunIdRoute: AuditRunsRunIdRoute,
  LabQueriesVariantRoute: LabQueriesVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
